version: 2

terraform: &terraform
  working_directory: ~/repo
  docker:
    - image: hashicorp/terraform:0.12.21
  context: aws
  environment:
    TF_IN_AUTOMATION: true

# To use with Ansible
awscli: &awscli
  working_directory: ~/repo
  docker:
    - image: hachikoapp/awscli:1.0.0
  environment:
    TF_IN_AUTOMATION: true

jobs:
  init:
    <<: *terraform
    steps:
      - checkout
      - run: 
          name: init
          command: |
            export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
            export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            echo $AWS_DEFAULT_REGION
            terraform init -input=false
      - persist_to_workspace:
          root: ~/repo
          paths: .
  plan:
    <<: *terraform   
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: plan
          command: terraform plan
      - store_artifacts:
          path: ~/repo/tfplan
          destination: tfplan
      - persist_to_workspace:
          root: ~/repo
          paths: .          
  apply:
    <<: *terraform
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: apply
          command: terraform apply -auto-approve 
      - run:
          name: show
          command: terraform show -no-color > tfresult
      - store_artifacts:
          path: ~/repo/tfresult
          destination: tfresult  
  destroy_app:
    <<: *terraform
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: destroy app
          command: terraform destroy -auto-approve
workflows:
  version: 2
  build_deploy:
    jobs:
      - init
      - plan:
          requires:
            - init
      - apply:
          requires:
            - plan
          filters:
            branches:
              only: 
                - master
      - destroy_app:
          filters:
            branches:
              only:
                - destroy