---
# tasks file for app

- name: Installing httpd
  yum:
    name:
      - httpd
      - php-mysql
      - mod_php
    use_backend: yum

- name: Starting httpd service
  service: name=httpd state=started

# - name: Upload files
#   copy: src=index.php dest={{ dest }}
#   register: HTTPD_Restarted