---

# Playbook for app server

- name: app server
  hosts: tag_Name_App01 #ec2.py dynamic tag tag_KEY_VALUE where KEY=Name and VALUE=App01
  become: yes
  gather_facts: no

  roles:
    - app
    
  vars:
    rds_endpoint: '{{ db_endpoint }}'